import Contact from "./cards"



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children, children2}) {
  return (
    <html lang="en">
      <body >
        {children}
      </body>
      
    </html>
  )
}
